#!/bin/bash

PLUGIN_PATH='./skype-gnome-plugin.py'

procCount() {
  ps -U $USER -o fname | egrep "^$1$" | wc -l
}

skypeCount() {
  procCount skype
}

SKYPE_COUNT=`skypeCount`
if [ $SKYPE_COUNT -eq 0 ] ; then
  echo 'Start skype'
  skype &
  sleep 0.5
fi

SKYPE_COUNT=`skypeCount`
while [ $SKYPE_COUNT -ge 1 ] ; do
  echo 'Start plugin'
  eval $PLUGIN_PATH
  echo 'Skype plugin finished'
  sleep 0.5
  SKYPE_COUNT=`skypeCount`
done

echo 'Done'
